ServerEvents.recipes(event => {
    event.replaceInput({}, "minecraft:barrel", "#tfcbarrels:barrels")
    event.replaceInput({}, "mca:rose_gold_ingot", "#forge:ingots/rose_gold")

    event.replaceInput({}, "minecraft:emerald", "#forge:gems/emerald")
    event.replaceInput({}, "minecraft:lapis_lazuli", "#forge:gems/lapis")
    event.replaceInput({}, "minecraft:diamond", "#forge:gems/diamond")
    event.replaceInput({}, "minecraft:gold_ingot", "#forge:ingots/gold")
    event.replaceInput({}, "minecraft:iron_ingot", "#forge:ingots/iron")
    event.replaceInput({}, "minecraft:copper_ingot", "#forge:ingots/copper")
    event.replaceInput({}, "minecraft:iron_bars", "tfc:metal/bars/wrought_iron")
    event.replaceInput({}, "minecraft:kelp", "tfc:plant/leafy_kelp")
    event.replaceInput({}, "minecraft:string", "#forge:string")
    event.replaceInput({}, "minecraft:rabbit_hide", "#forge:leather")
    event.replaceInput({}, "farmersdelight:straw", "#forge:straw")

    event.replaceOutput({}, "minecraft:emerald", "tfc:gem/emerald")
    event.replaceOutput({}, "minecraft:diamond", "tfc:gem/diamond")
    event.replaceOutput({}, "farmersdelight:straw", "tfc:straw")

    let mcaFilter = {mod: "mca"}
    event.replaceInput(mcaFilter, "minecraft:oak_sapling", "tfc:wood/sapling/oak")
    event.replaceInput(mcaFilter, "minecraft:poppy", "tfc:plant/poppy")
    event.replaceInput(mcaFilter, "minecraft:wheat_seeds", "tfc:seeds/wheat")
    event.replaceInput(mcaFilter, "minecraft:cobblestone", "#forge:smooth_stone")
    event.replaceInput(mcaFilter, "minecraft:stone", "tfc:seeds/wheat")
    event.replaceInput(mcaFilter, "minecraft:oak_planks", "tfc:wood/planks/oak")
    event.replaceInput(mcaFilter, "minecraft:oak_fence", "tfc:wood/planks/oak_fence")
    event.replaceInput(mcaFilter, "minecraft:spruce_planks", "tfc:wood/planks/spruce")
    event.replaceInput(mcaFilter, "minecraft:spruce_fence", "tfc:wood/planks/spruce_fence")
    event.replaceInput(mcaFilter, "minecraft:birch_planks", "tfc:wood/planks/birch")
    event.replaceInput(mcaFilter, "minecraft:birch_fence", "tfc:wood/planks/birch_fence")
    event.replaceInput(mcaFilter, "minecraft:acacia_planks", "tfc:wood/planks/acacia")
    event.replaceInput(mcaFilter, "minecraft:acacia_fence", "tfc:wood/planks/acacia_fence")
})
