# magical_relics:magical_relics_abilities/lightning.toml
# This config contains options for the magical_relics:lightning ability.


# Category: general
# General settings for this ability.

  # The rarity of this ability. Primarily only determines the color of the ability's description.
  # <Enum> Valid Values: { "common", "uncommon", "rare", "epic", "magical_relics:mundane", "magical_relics:glorious"
  #   }, Default: "magical_relics:mundane"
  general.rarity = "magical_relics:mundane"


# Category: cooldown
# Settings for this ability's cooldown.

  # The number of ticks to put this ability on cooldown for after use.
  # <Number> Range: 0.0 ~ 9.223372036854776E18, Default: 100.0
  cooldown.cooldown = 100


# Category: lightning
# Options for the lightning summoned by this ability.

  # If enabled, the player summoning the lightning will not be damaged by it.
  # <Boolean> Valid Values: { true, false }, Default: true
  lightning.immune_summoner = true
