#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Dec 15 23:22:00 AMT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
