# 
#Temperature difference growth rate. If the value is higher, the temperature of the crude crucible being heated will increase faster according to the temperature difference
#温差增长率。若该数值越高，被加热的简陋坩埚的温度会根据温差增长速度越快。
#Range: 0.0 ~ 1.0
temperatureDifferenceGrowthRate = 0.005

